# This pipeline uses all alpine images. Try adding a breakpoint before the first step and running commands like `ls` to explore the volume.
version: '1.0'
stages:
  - "Stage 1"
  - "Stage 2"
  - "Stage 3"
steps:
  one:
    title: One Step
    stage: "Stage 1"
    image: alpine
    commands:
      - echo '******* hello world *******'
  two:
    title: Two Step
    stage: "Stage 1"
    image: alpine
    commands:
      - echo '******* hello world *******'
  three:
    title: Three Step
    stage: "Stage 1"
    image: alpine
    commands:
      - echo '******* hello world *******'
      
  four:
    type: parallel
    stage: "Stage 2"
    steps:
    
        red:
          title: Red Step
          image: alpine
          commands:
            - echo '******* hello world *******'
            
        green:
          title: Green Step
          image: alpine
          commands:
            - echo '******* hello world *******'
            
        blue:
          title: Blue step
          image: alpine
          commands:
            - echo '******* hello world *******'
            
  final_stage:
    title: Final Stage
    stage: "Stage 3"
    image: alpine
    commands:
      - echo '******* hello world *******'   